In [32]:
import pandas as pd

file_path = r'C:\Users\nekan\Desktop\HUS\2025-HOSPITAL\prueba5enf.xlsx'
df = pd.read_excel(file_path)
df.head()

,Unnamed: 0,S,D,L,M,X,J,V,S.1,D.1,...,S.3,D.3,L.3,M.3,X.3,J.3,V.3,S.4,D.4,L.4
0,Nº empleado,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
1,E101,M,M,N,N,-,-,L,L,L,...,L,L,M,M,M,N,N,-,-,L
2,E102,L,L,M,M,N,-,L,M,M,...,-,N,N,-,-,L,L,L,L,M
3,E103,M,L,M,M,L,M,M,L,L,...,N,N,-,-,L,M,M,M,M,N
4,E104,L,L,M,M,M,N,N,-,-,...,M,M,N,N,-,-,L,L,L,M

In [ ]:
df = df.drop(index=0)  
df.reset_index(drop=True, inplace=True) 
df.head()

,Unnamed: 0,S,D,L,M,X,J,V,S.1,D.1,...,S.3,D.3,L.3,M.3,X.3,J.3,V.3,S.4,D.4,L.4
0,E101,M,M,N,N,-,-,L,L,L,...,L,L,M,M,M,N,N,-,-,L
1,E102,L,L,M,M,N,-,L,M,M,...,-,N,N,-,-,L,L,L,L,M
2,E103,M,L,M,M,L,M,M,L,L,...,N,N,-,-,L,M,M,M,M,N
3,E104,L,L,M,M,M,N,N,-,-,...,M,M,N,N,-,-,L,L,L,M
4,E105,T,T,L,T,T,T,T,T,L,...,L,T,T,T,T,L,T,L,T,L

In [34]:
first_column_values = df.iloc[:, 0].values
print(first_column_values)

['E101' 'E102' 'E103' 'E104' 'E105']

In [35]:
df.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)
df.head()

,ID,S,D,L,M,X,J,V,S.1,D.1,...,S.3,D.3,L.3,M.3,X.3,J.3,V.3,S.4,D.4,L.4
0,E101,M,M,N,N,-,-,L,L,L,...,L,L,M,M,M,N,N,-,-,L
1,E102,L,L,M,M,N,-,L,M,M,...,-,N,N,-,-,L,L,L,L,M
2,E103,M,L,M,M,L,M,M,L,L,...,N,N,-,-,L,M,M,M,M,N
3,E104,L,L,M,M,M,N,N,-,-,...,M,M,N,N,-,-,L,L,L,M
4,E105,T,T,L,T,T,T,T,T,L,...,L,T,T,T,T,L,T,L,T,L

In [ ]:
new_column_names = {df.columns[i]: i-1 for i in range(1, len(df.columns))}
df.rename(columns=new_column_names, inplace=True)
df.head()

     ID  0  1  2  3  4  5  6  7  8  ... 21 22 23 24 25 26 27 28 29 30
0  E101  M  M  N  N  -  -  L  L  L  ...  L  L  M  M  M  N  N  -  -  L
1  E102  L  L  M  M  N  -  L  M  M  ...  -  N  N  -  -  L  L  L  L  M
2  E103  M  L  M  M  L  M  M  L  L  ...  N  N  -  -  L  M  M  M  M  N
3  E104  L  L  M  M  M  N  N  -  -  ...  M  M  N  N  -  -  L  L  L  M
4  E105  T  T  L  T  T  T  T  T  L  ...  L  T  T  T  T  L  T  L  T  L

[5 rows x 32 columns]

In [37]:
id_categories = {}

for column in df.columns[1:]:  # Skip the 'ID' column
    id_categories[column] = {'M': [], 'T': [], 'N': []}
    for idx, value in enumerate(df[column]):
        if value in ['M', 'T', 'N']:
            id_categories[column][value].append(df['ID'][idx])

print(id_categories)

{0: {'M': ['E101', 'E103'], 'T': ['E105'], 'N': []}, 1: {'M': ['E101'], 'T': ['E105'], 'N': []}, 2: {'M': ['E102', 'E103', 'E104'], 'T': [], 'N': ['E101']}, 3: {'M': ['E102', 'E103', 'E104'], 'T': ['E105'], 'N': ['E101']}, 4: {'M': ['E104'], 'T': ['E105'], 'N': ['E102']}, 5: {'M': ['E103'], 'T': ['E105'], 'N': ['E104']}, 6: {'M': ['E103'], 'T': ['E105'], 'N': ['E104']}, 7: {'M': ['E102'], 'T': ['E105'], 'N': []}, 8: {'M': ['E102'], 'T': [], 'N': []}, 9: {'M': ['E101', 'E102', 'E103'], 'T': ['E105'], 'N': []}, 10: {'M': ['E101', 'E103', 'E104'], 'T': [], 'N': ['E102']}, 11: {'M': ['E103', 'E104'], 'T': ['E105'], 'N': ['E101']}, 12: {'M': ['E104'], 'T': [], 'N': ['E103']}, 13: {'M': ['E102', 'E104'], 'T': ['E105'], 'N': ['E103']}, 14: {'M': ['E101'], 'T': ['E105'], 'N': ['E104']}, 15: {'M': ['E101'], 'T': ['E105'], 'N': ['E104']}, 16: {'M': ['E101', 'E102'], 'T': ['E105'], 'N': []}, 17: {'M': ['E102'], 'T': [], 'N': []}, 18: {'M': ['E101', 'E102', 'E103'], 'T': ['E105'], 'N': []}, 19: {'M': ['E101', 'E103', 'E104'], 'T': ['E105'], 'N': ['E102']}, 20: {'M': ['E101', 'E103', 'E104'], 'T': ['E105'], 'N': ['E102']}, 21: {'M': ['E104'], 'T': [], 'N': ['E103']}, 22: {'M': ['E104'], 'T': ['E105'], 'N': ['E102', 'E103']}, 23: {'M': ['E101'], 'T': ['E105'], 'N': ['E102', 'E104']}, 24: {'M': ['E101'], 'T': ['E105'], 'N': ['E104']}, 25: {'M': ['E101'], 'T': ['E105'], 'N': []}, 26: {'M': ['E103'], 'T': [], 'N': ['E101']}, 27: {'M': ['E103'], 'T': ['E105'], 'N': ['E101']}, 28: {'M': ['E103'], 'T': [], 'N': []}, 29: {'M': ['E103'], 'T': ['E105'], 'N': []}, 30: {'M': ['E102', 'E104'], 'T': [], 'N': ['E103']}}